name: ${project.artifactId}
main: id.au.jsaunders.${project.artifactId}.${project.artifactId}
version: ${project.version}

commands:
    radio:
        description: The main command for AtomicRadio.
        usage: /<command> (on [shoutcast,dubtrack], off, bc/broadcast, reload, req/request [text], reqlist [num,del[num,all]])

permissions:
    atomicradio.admin:
        description: Gives access to all radio commands
        children:
            atomicradio.status: true
        default: op
    atomicradio.use:
        description: Gives access to DJ commands